# Generated by Django 5.2.6 on 2025-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('applied_class', models.CharField(choices=[('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SS1', 'SS 1'), ('SS2', 'SS 2'), ('SS3', 'SS 3')], max_length=10)),
                ('former_school', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_address', models.TextField()),
                ('school_city', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
