# Generated by Django 5.2.6 on 2025-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='applied_class',
            field=models.CharField(choices=[('Nursery1', 'Nursery 1'), ('Nursery2', 'Nursery 2'), ('Nursery3', 'Nursery 3'), ('Primary1', 'Primary 1'), ('Primary2', 'Primary 2'), ('Primary3', 'Primary 3'), ('Primary4', 'Primary 4'), ('Primary5', 'Primary 5'), ('Primary6', 'Primary 6'), ('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SS1', 'SS 1'), ('SS2', 'SS 2'), ('SS3', 'SS 3')], max_length=10),
        ),
    ]
