# Generated by Django 5.2.6 on 2025-10-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
